import type { Env } from '../types';
import { logo, page } from './shared';

export function loginPage(env: Env): string {
  const body = `<main class="auth-page"><a class="auth-brand" href="/"><img src="/logo.svg" alt=""><span>Sakura Mail</span></a><section class="auth-card"><div class="eyebrow">Passwordless and protected</div><h1>Sign in or create your account</h1><p>Enter your email and we’ll send a one-time code — no password to choose, remember or reset. If you’re new, entering the code creates your private workspace automatically.</p>
    <form id="login-start-form"><label>Email address<input type="email" name="email" autocomplete="email" placeholder="you@company.com" required></label><div id="turnstile-box"></div><button class="button primary large full" type="submit">Send verification code</button></form>
    <form id="login-verify-form" hidden><label>Six-digit code<input type="text" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" placeholder="000000" required></label><button class="button primary large full" type="submit">Verify and continue</button><button class="button text full" type="button" id="restart-login">Use a different email</button></form>
    <div class="form-message" id="auth-message" aria-live="polite"></div><p class="auth-legal">By continuing, you agree to the <a href="/terms">Terms</a> and acknowledge the <a href="/privacy">Privacy Policy</a>.</p></section></main>`;
  return page('Sign in', body, env);
}

export function dashboardPage(env: Env): string {
  const body = `<div class="app-shell"><aside class="sidebar">${logo}<nav><button data-view="overview" data-tip="Your workspace at a glance: credits, contacts, deliverability and recent campaigns." class="active">Overview</button><button data-view="campaigns" data-tip="Compose, preview, test, schedule and send email campaigns.">Campaigns</button><button data-view="reports" data-tip="Deliverability, opens, clicks and per-recipient engagement.">Reports</button><button data-view="contacts" data-tip="Your encrypted recipient list with tags, consent and import.">Contacts</button><button data-view="segments" data-tip="Build reusable audiences from tags, consent and dates.">Segments</button><button data-view="files" data-tip="Attachments stored in Cloudflare R2 (5 MiB max).">Files</button><button data-view="billing" data-tip="Buy prepaid email credits with PayPal — $1 per 1,000.">Billing</button><button data-view="settings" data-tip="Business identity, postal address and sender addresses.">Settings</button><button data-view="admin" id="admin-nav" data-tip="Platform-wide totals (aggregate only, no recipient data)." hidden>Platform admin</button></nav><div class="sidebar-footer"><span id="sidebar-email">Loading…</span><button id="logout-button">Sign out</button></div></aside>
    <main class="app-main"><header class="app-header"><div><button class="mobile-menu" id="mobile-menu">☰</button><h1 id="view-title">Overview</h1><p id="view-subtitle">Your campaign workspace at a glance.</p></div><button class="button primary" data-action="new-campaign">+ New campaign</button></header>
      <div id="app-alert" class="app-alert" hidden></div>
      <section id="view-root" class="view-root"><div class="loading-card">Loading your encrypted workspace…</div></section>
    </main>
  </div>
  <dialog id="campaign-dialog" class="modal"><form method="dialog" id="campaign-form"><div class="modal-head"><div><div class="eyebrow">Campaign builder</div><h2 id="campaign-dialog-title">Create a mailing</h2></div><button class="icon-button" value="cancel" aria-label="Close">×</button></div>
    <div class="template-bar"><label>Start from a template<select id="template-pick"><option value="">Blank campaign</option></select></label><div class="template-bar-actions"><button type="button" class="button text" id="delete-template" hidden>Delete</button><button type="button" class="button ghost" id="save-template">Save as template</button></div></div>
    <div class="form-grid"><label>Campaign name<input name="name" required maxlength="120" placeholder="Spring product update"></label><label class="field-hint" data-tip="Use merge fields like {{first_name}}, {{last_name}} or {{email}} to personalise each message.">Subject line<input name="subject" required maxlength="998" placeholder="A fresh update for {{first_name}}"></label><label class="field-hint" data-tip="Preview text most inboxes show right after the subject. Around 40–100 characters works best.">Preheader / preview text<input name="preheader" maxlength="255" placeholder="Shown after the subject in most inboxes"></label><label class="field-hint" data-tip="The verified From address recipients receive the mail from. Must be on your sending domain.">Sender identity<select name="senderId" required></select></label><label class="field-hint" data-tip="The friendly name recipients see, e.g. 'Alex from Acme'. This is the most visible part of the From line.">Display name (recipients see this)<input name="fromName" maxlength="100" placeholder="Uses the sender default"></label><label class="field-hint" data-tip="Where replies go. Can be any inbox — it does not have to match the sending domain.">Reply-to (any inbox)<input name="replyTo" type="email" placeholder="Uses the sender default"></label><label class="field-hint" data-tip="The base audience. Combine with re-engagement below, e.g. VIP customers who didn't open the launch email.">Audience segment<select name="segmentId"><option value="">All active contacts</option></select></label><label class="field-hint" data-tip="Target people by how they engaged with an earlier campaign. 'Didn't open' only counts people the campaign was actually delivered to.">Re-engagement (optional)<select name="engagementFilter"><option value="any">Everyone in the audience</option><option value="not_opened">Did not open…</option><option value="opened">Opened…</option><option value="not_clicked">Did not click…</option><option value="clicked">Clicked…</option></select></label><label class="field-hint" data-tip="Which earlier campaign to measure engagement against. Only campaigns that were sent with tracking will have data.">Based on campaign<select name="engagementCampaignId"><option value="">Choose a campaign</option></select></label><label>Schedule (optional)<input name="scheduledAt" type="datetime-local"></label><div class="audience-estimate" id="audience-estimate">Audience will be calculated from active, unsuppressed contacts.</div></div>
    <fieldset class="tracking-toggles"><legend>Engagement tracking</legend><label class="check-label"><input type="checkbox" name="trackOpens"> Track opens <small>invisible pixel</small></label><label class="check-label"><input type="checkbox" name="trackClicks"> Track clicks <small>links redirect through this app</small></label><p class="price-note">Off by default. When enabled, the message footer discloses measurement to recipients. Opens are approximate (Apple Mail Privacy Protection pre-fetches images). Ensure tracking complies with your privacy policy and local consent laws.</p></fieldset>
    <label>HTML message<textarea name="htmlBody" rows="12" required placeholder="<h1>Hello {{first_name}}</h1><p>Your message…</p>"></textarea></label><label>Plain-text fallback<textarea name="textBody" rows="6" placeholder="Hello {{first_name}}, …"></textarea></label>
    <div id="attachment-picker" class="attachment-picker"></div><div class="modal-actions"><button class="button text" type="button" id="preview-campaign" data-tip="See how your email looks on desktop and mobile before saving.">Preview</button><button class="button ghost" value="cancel">Cancel</button><button class="button primary" type="submit" value="default" id="campaign-submit">Save campaign</button></div></form></dialog>
  <dialog id="preview-dialog" class="modal"><div class="modal-head"><div><div class="eyebrow" id="preview-subject">Subject</div><h2 id="preview-preheader">Preview</h2></div><div class="preview-controls"><button type="button" class="button ghost" data-device="desktop">Desktop</button><button type="button" class="button ghost" data-device="mobile">Mobile</button><button class="icon-button" id="preview-close" aria-label="Close">×</button></div></div><div class="preview-stage"><div id="preview-host" class="preview-host desktop"></div></div></dialog>
  <dialog id="contact-dialog" class="modal compact"><form method="dialog" id="contact-form"><div class="modal-head"><div><div class="eyebrow">Add contact</div><h2>One recipient</h2></div><button class="icon-button" value="cancel">×</button></div><label>Email<input type="email" name="email" required></label><div class="form-grid"><label>First name<input name="firstName"></label><label>Last name<input name="lastName"></label></div><label>Consent status<select name="consentStatus"><option value="express">Express</option><option value="implied">Implied</option><option value="transactional">Transactional</option><option value="unknown">Unknown</option></select></label><label>Consent source<input name="consentSource" placeholder="Website signup form"></label><label>Tags<input name="tags" placeholder="customer, newsletter, spring-2026"><small>Separate tags with commas.</small></label><div class="modal-actions"><button class="button ghost" value="cancel">Cancel</button><button class="button primary" type="submit">Add contact</button></div></form></dialog>`;
  return page('Dashboard', body, env, { app: true });
}
